### ISSUE TITLE
Bug: Crashing on start-up

### ISSUE THREAD

**Issue by Legoman249** [The-Aether-Team/Cumulus#21]
### What Feature Types Apply to This Bug?

Config, Other (Please Describe)

### Other Type

Error on start up: java.lang.IllegalStateException: Registry not present for DeferredHolder{ResourceKey[cumulus_menus:menu / cumulus_menus:minecraft]}: cumulus_menus:menu

### What Type of Bug Is This?

Compatibility

### Forge Version

Neo 21.1.76

### Cumulus Version

1.1.2

### Is This Bug a Conflict With Another Mod?

Keepers of the stones II 1.0.1, L2 artifacts 3.0.0+6, Nether based materials 1.0.6

### Client Log

<script src="https://gist.github.com/Legoman249/9598f551d3f4ad182f11cb12816001ee.js"></script>

### Crash Report (if applicable)

<script src="https://gist.github.com/Legoman249/31730356b02f0bff7f8293f15684128d.js"></script>

### Steps to Reproduce

Issue occured after installing Cummulus and Aether Mod into personal modpack
Went through every mod installed to find conflicts
Unknown if can be reproduced with just the listed conflict alone or if other mods in list are also causing conflict. 

### What You Expect To Happen

As none of these mods add or change a main menu screen, assumed game may function normally. 

### What Actually Happened

Game crash on startup with error:
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Registry not present for DeferredHolder{ResourceKey[cumulus_menus:menu / cumulus_menus:minecraft]}: cumulus_menus:menu

### Additional Details

Even after disabling and removing cummulus from mod list through curseforge, error still occurs. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Can you provide logs with only the conflicting mods installed?

**Comment by Legoman249** [comment]
Solo installed mods (With cumulus):
L2 - https://gist.github.com/Legoman249/d243ddf5e3e6eb35c30ad0a3e6155371
NBM - https://gist.github.com/Legoman249/f63d3c0d8f9680fbc074624a12c50bcc
Got keepers of stone to work - unsure of issue there
L2 and NBM installed (With Cumulus)
https://gist.github.com/Legoman249/04929678af2cf017902ee899859fb93c

**Comment by Legoman249** [comment]
Fixed issue,
Missing mod dependency somewhere
