### ISSUE TITLE
Bug: Cumulus Crashing After Adding Aether

### ISSUE THREAD

**Issue by theboo** [The-Aether-Team/Cumulus#22]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Crash during pack load

### What Type of Bug Is This?

Crash

### Forge Version

21.1.74(also tried 77 which is current latest)

### Cumulus Version

1.1.2(im guessing this is being shadow jarred in aether because i do not have it installed myself)

### Is This Bug a Conflict With Another Mod?

possibly, this is adding to enigmatica 10

### Client Log

https://mclo.gs/LCWmnFr

### Crash Report (if applicable)

https://mclo.gs/nZdVGfX

### Steps to Reproduce

add aether and owo to enigmatica 10 v1.13.0

launch pack

crash

### What You Expect To Happen

not crash

### What Actually Happened

crashed

### Additional Details

we're looking in to adding aether to enigmatica 10 to see if we want to add it to the pack! I do not currently have time to binary test this by removing mods until it stops happening, hoping y'all might have some insight... i have tried removing sodium, iris and pack menu and this did not help.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by theboo** [comment]
forgot to mention, we do not have any of the mods mentioned in #21 so im guessing this is a more widespread issue than incompat with one or two mods..

**Comment by bconlon1** [comment]
Hmm, could you possibly see if you're missing some other dependency for another mod? Similar to the other report.

**Comment by bconlon1** [comment]
Although I guess that'd be weird if its for an already-made modpack like enigmatica.

**Comment by theboo** [comment]
yeah i'm on the enigmatica team, just attempted to add it to enigmatica 10 v 1.13.0 and get the above crash... normally i would do the binary testing to figure out what the problem mod is, i just do not have the time currently... and with it being an issue with 3 other mods previously, who knows if the issue pops up with multiple mods in our pack(like if i test it down to a single mod, that doesnt mean the issue doesnt occur with 2-3 other mods we have)

edit: im also unclear how missing a dep for another mod would cause this crash lol... im curious if we dont have all the information from that previous issue

**Comment by bconlon1** [comment]
Maybe, since I'm confused how that fixed the previous issue as well.

**Comment by bconlon1** [comment]
My only idea is maybe this could happen if there is a screen from another mod opened up early enough before Cumulus registration occurs, then it would try to perform the menu initialization before the registry exists. Maybe I can safely add a check for ensuring the registry exists before that code runs; it should still run later on once a starting screen is opened after the registration phase. I can make a hotfix for this later for testing with.

Maybe the previous issue was fixed because a missing dependency caused an early screen to open too or something.

**Comment by bconlon1** [comment]
Would you be able to test if this development build of Cumulus fixes the issue? https://output.circle-artifacts.com/output/job/31a3d1a7-447e-4395-8164-3198028aa84f/artifacts/0/~/project/build/libs/cumulus_menus-1.21.1-1.1.2-neoforge.jar

**Comment by theboo** [comment]
Will do as soon as I get off work, or I'll ask one of the other contributors.. will this override the version jij'd in the aether,  or should I load this without aether? Unsure if this crash needs the menus the aether adds

**Comment by theboo** [comment]
Using test jar, no crash without aether installed, same crash with aether installed. Can't tell from the crash log if it's because aether is using the jij'd cumulus since they both have the same version number haha
https://mclo.gs/WH8rdnJ

**Comment by theboo** [comment]
Just tried loading the pack with the release version of cumulus(<https://www.curseforge.com/minecraft/mc-mods/cumulus/files/5895856>) and it also doesn't crash...

This tells me aether's cumulus menus are required for this crash to happen, and either the test jar did not help or the test jar is not taking precedent over the jij'd cumulus that ships with the aether so it continues to crash due to using the released version of 1.1.2 existing...

Would need a test build of aether either without cumulus packaged with it so I can use the test jar you sent with the aether, or I would need a test build of the aether that includes the test build of cumulus, I think...

**Comment by bconlon1** [comment]
Interesting, that makes this even weirder.

**Comment by bconlon1** [comment]
Aether without Cumulus: https://output.circle-artifacts.com/output/job/d0631537-3deb-4cac-b1a9-fd48ca0fc3ba/artifacts/0/~/project/build/libs/aether-1.21.1-1.5.1-beta.3-neoforge.jar

Another Cumulus build with hopefully a better check for the registry crash: https://output.circle-artifacts.com/output/job/f192bd94-2d87-4681-8d44-68df30f90259/artifacts/0/~/project/build/libs/cumulus_menus-1.21.1-1.1.2-neoforge.jar

**Comment by theboo** [comment]
Similar crash but it's aether in the stacktrace now instead of cumulus! Progress?

https://mclo.gs/rL0fONj

**Comment by bconlon1** [comment]
I guess now I just make the same fix there for Aether

**Comment by bconlon1** [comment]
Actually I could maybe change some more code in Cumulus a bit so the fix doesn't have to be on the end of any mod using it.

**Comment by theboo** [comment]
Just gotta believe

**Comment by bconlon1** [comment]
Aether jar including new fixes in both mods that hopefully work: https://output.circle-artifacts.com/output/job/a7988bd0-505b-4364-9140-64f5b6a09f14/artifacts/0/~/project/build/libs/aether-1.21.1-1.5.1-beta.3-neoforge.jar

**Comment by theboo** [comment]
New crash? Unsure if related to current fix or if I should make a new issue on the aether tracker, but here's the crash report... Looks like it's trying to read from config before the config is loaded?

https://mclo.gs/OKFTrTO

Let me know if you want me to move this to a new issue on the aether repo tracker

**Comment by bconlon1** [comment]
Well I guess this crash seems to confirm it is in fact a screen from a mod being opened incredibly early in the game loading process if both registry info and config info doesn't exist. I'll continue looking into it for this ticket.

**Comment by bconlon1** [comment]
New fix: https://output.circle-artifacts.com/output/job/6c2af772-4c38-4e90-8d0a-a54096485389/artifacts/0/~/project/build/libs/aether-1.21.1-1.5.1-beta.3-neoforge.jar

Wouldn't be surprised if it doesn't work since its a bit stupid but I'm curious.

**Comment by theboo** [comment]
Still config crash but looks like different lines?
https://mclo.gs/dQSp5y7

**Comment by bconlon1** [comment]
Yet another fix: https://output.circle-artifacts.com/output/job/d444a4d9-fa32-48b6-95aa-33963e1a45f7/artifacts/0/~/project/build/libs/aether-1.21.1-1.5.1-beta.3-neoforge.jar I wonder what mod is leading to this.

**Comment by MuteTiefling** [comment]
Just nosing in here so I can reply more directly, since I've been doing the tests for Boo :D

Here's from that last attempt. Still crashing, but very different: https://mclo.gs/1HnEszT

**Comment by theboo** [comment]
Looks like we may have found(at least one of) the mod leading to this? Lol

**Comment by bconlon1** [comment]
Since another mod is being pointed to now, maybe whatever mod is opening an early screen is also crashing this mod too? I would have to look at their code.

**Comment by bconlon1** [comment]
Interesting, gigaherz says that the crash is caused by something else https://github.com/gigaherz/ToolBelt/issues/154.

**Comment by bconlon1** [comment]
Can you provide the full client log now?

**Comment by MuteTiefling** [comment]
Yeah, I've seen that as well with similar errors. Removing that mod would likely just point to something else. 

Anyhoo, here's fresh logs
Crash: https://mclo.gs/TGh5qxx
Latest: https://mclo.gs/iFySY3P

**Comment by bconlon1** [comment]
In a dumb turn of events, it seems the crash might have been related to Small Ships the entire time 😭, the same error has been reported to us before and it seems to be an issue with some kind of compatibility that Small Ships implements for other mods assumedly with new wood types not working (hard to tell since the mod is closed source): https://github.com/The-Aether-Team/The-Aether/issues/2346.

I would recommend bringing this up in their Discord since they don't have an issue tracker and I've tried opening a post already for it but it hasn't gotten much attention.

**Comment by bconlon1** [comment]
Although there did seem to still be some kind of error with Cumulus since another player stopped getting the crash with a test build, so I will be publishing that later at least.

**Comment by MuteTiefling** [comment]
Alright, thanks for your time and effort on this. it's very much appreciated

**Comment by theboo** [comment]
just fyi, small ships is sauce available, just is not advertised anywhere... In another hilarious turn of events, this same error was reported there but with twilight forest instead of aether... And it was reported by our "boss" the owner of Enigmatica packs lmao... and again, thank you so much for all your work even if we just went around in a giant circle haha, not a ton of mod devs would have gone that far, especially that quickly!!

https://github.com/talhanation/smallships

edit: i doubt it gets fixed any time soon, small ships has not received an update since the very first jar after porting to 1.21.1 in august..

also pack loads fine with it removed

**Comment by bconlon1** [comment]
Oh interesting, iirc someone else also thought it was closed source, so I didn't think to look deeper for whether it actually was or not, assumedly because they also didn't see the source advertised and thus I couldn't find it either lol. I guess this means I can narrow down the issue on their end.

**Comment by MuteTiefling** [comment]
I've reported this here: https://discord.com/channels/903372103888289812/1308179480937889884

Seems someone else has also reported it there https://discord.com/channels/903372103888289812/1306321629881565284

All the reports! :D

**Comment by bconlon1** [comment]
Ah yeah that would be my report.

I think I immediately know what's going on with the bug from seeing the source, https://github.com/talhanation/smallships/blob/b9975e1f3203de0116345f094672074d49998af2/common/src/main/java/com/talhanation/smallships/world/item/ModItems.java#L28 actually registers cogs according to BoatType not WoodType (makes more sense now considering the mod), and I think they haven't accounted for NeoForge allowing that enum to be extended and have new types added that include mod ids in the name. Although that makes me wonder if NeoForge recommends putting the id in the name with the `modid:name` format or not. I'll ask around a bit.

**Comment by MuteTiefling** [comment]
Awesome, thanks! Hadn't made the link between the two users. <3
