### ISSUE TITLE
Bug: Crash on startup with Twilight Forest

### ISSUE THREAD

**Issue by sm644me** [The-Aether-Team/Cumulus#9]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

45.1.0

### Cumulus Version

0.3.1

### Is This Bug a Conflict With Another Mod?

Twilight Forest 4.2.1696

### Crash Report (if applicable)

https://gist.github.com/sm644me/9849502f52aa8406cfcf51eb289aea89

### Steps to Reproduce

1. Install the latest Aether CircleCI build.
2. Install Twilight Forest.
3. Launch the game.
4. Crash. This crash is so early that there is no latest.log to provide.

### What You Expect To Happen

I expect the game to not crash.

### What Actually Happened

The game crashed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Conflict between https://github.com/The-Aether-Team/Cumulus/blob/1.19.4-develop/src/main/java/com/aetherteam/cumulus/mixin/mixins/client/MusicManagerMixin.java and https://github.com/TeamTwilight/twilightforest/blob/1.20.x/src/main/java/twilightforest/ASMHooks.java#L126 (https://github.com/TeamTwilight/twilightforest/blob/1.19.x/src/main/resources/META-INF/asm/music.js)
